export const atracciones = [
    {
        nombre: "La Rodadora",
        heroURL: './assets/heros/la-rodadora.jpg',
        imagen: "./assets/La Rodadora 1.jpg",
        informacion: 'La Rodadora es un museo interactivo y centro de ciencias ubicado en Ciudad Juárez, Chihuahua, México. Fundado en 2004, este museo ha sido un importante centro de aprendizaje y entretenimiento para personas de todas las edades en la región. A continuación, te proporcionaré un informe completo sobre el Museo La Rodadora, destacando sus características principales y su contribución a la comunidad. ',
        informacion2: "La Rodadora se inauguró en 2004 con el propósito de brindar a la comunidad de Ciudad Juárez y sus alrededores un espacio dedicado a la educación, la ciencia y la cultura. Desde su apertura, el museo ha evolucionado y se ha expandido continuamente para ofrecer nuevas exposiciones y programas educativos. ",
        horarios: "Los horarios de funcionamiento y los precios de entrada pueden variar según la temporada y las exposiciones temporales. Se recomienda verificar los detalles actuales en el sitio web oficial del museo antes de planificar una visita. ",
        direccion: "Calle Jesús Soltero Lozoya y Blvd. Teófilo Borunda, Del Norte, Comunitario Jarudo, 32652 Cd Juárez, Chih.",
        googleMaps: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3394.9499492810864!2d-106.4306998236102!3d31.68993617413683!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x86e75c320bf457f7%3A0x5e3f28d1f3b206f8!2sLa%20Rodadora%20Espacio%20Interactivo!5e0!3m2!1ses-419!2smx!4v1696299279410!5m2!1ses-419!2smx",
        sitioWeb: "http://www.larodadora.org/",
        facebook: "https://www.facebook.com/LaRodadora/",
        instagram: "https://www.instagram.com/larodadora/",
        tiktok: "https://www.tiktok.com/@larodadora ",
    },
    {
        nombre: "Museo de la Revolución en La Frontera",
        heroURL: './assets/heros/museo-de-la-revolucion-en-la-frontera.jpg',
        imagen: "./assets/Museo de la revolucion en la frontera 1.jpg",
        informacion: "La edificación atrae por sus contrastes arquitectónicos: Híbrido de múltiples elementos característicos de la arquitectura del siglo XIX. La ex aduana fue construida por el ingeniero Manuel Garfias entre 1885 y 1888 y su fin principal fue albergar la aduana fronteriza. Su inauguración formal se efectuó el 10 de septiembre de 1889, asistiendo como representante personal de Porfirio Díaz el Coronel Miguel Ahumada y el gobernador del estado Lauro Carrillo. ",
        informacion2: "Enmarcada por la avenidas 16 de septiembre, Benito Juárez, Vicente Guerrero y Francisco Villa emerge diferenciándose del contexto arquitectónico ubicado en el centro de Ciudad Juárez, un edificio conocido como la Ex Aduana, construcción que hoy alberga el Museo de la Revolución en la Frontera. ",
        horarios: "De martes a domingo de 9:00 a 17:00 horas. Los lunes permanece cerrado. Acceso gratuito.  Horario de Visitas Guiadas: De martes a viernes, de 9:00 a 17:00 horas. Duración de la Visita: 45 a 60 minutos. ",
        direccion: "Calle 16 de septiembre s/n Av. Juárez, Zona Centro Centro, 32000 Cd Juárez, Chih.",
        googleMaps: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3393.1684015643154!2d-106.48662722360866!3d31.7386040741148!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x86e75926dca66c2b%3A0x3adef4eb3d3b4a76!2sMuseo%20de%20la%20Revoluci%C3%B3n%20en%20la%20Frontera!5e0!3m2!1ses-419!2smx!4v1696299408172!5m2!1ses-419!2smx",
       sitioWeb: "https://sic.cultura.gob.mx/ficha.php?table=museo&table_id=1465", 
        gmail: "ifusioninah@yahoo.com.mx",
    },
    {
        nombre: "Monumento a la Mexicanidad",
        heroURL: "",
        imagen : "",
        informacion: "",
        informacion2: "",
        horarios: "",
        direccion: "",
        googleMaps: "",
        sitioWeb: "",
        facebook: "",
        instagram: "",
        tiktok: "",
        gmail: "",
    },
    {
        nombre: "La Casa de Juan Gabriel",
        heroURL: "",
        imagen : "",
        informacion: "",
        informacion2: "",
        horarios: "",
        direccion: "",
        googleMaps: "",
        sitioWeb: "",
        facebook: "",
        instagram: "",
        tiktok: "",
        gmail: "",
    },
    {
        nombre: "Centro Cultural Paso del Norte",
        heroURL: "",
        imagen : "",
        informacion: "",
        informacion2: "",
        horarios: "",
        direccion: "",
        googleMaps: "",
        sitioWeb: "",
        facebook: "",
        instagram: "",
        tiktok: "",
        gmail: "",
    },
    {
        nombre: "El Chamizal",
        heroURL: "",
        imagen : "",
        informacion: "",
        informacion2: "",
        horarios: "",
        direccion: "",
        googleMaps: "",
        sitioWeb: "",
        facebook: "",
        instagram: "",
        tiktok: "",
        gmail: "",
    },
    {
        nombre: "Catedral de Nuestra Señora de Guadalupe",
        heroURL: "",
        imagen : "",
        informacion: "",
        informacion2: "",
        horarios: "",
        direccion: "",
        googleMaps: "",
        sitioWeb: "",
        facebook: "",
        instagram: "",
        tiktok: "",
        gmail: "",
    },
]