export const atracciones = [
    {
        nombre: "La Rodadora",
        heroURL: './assets/heros/la-rodadora.jpg',
        imagen: "./assets/la-rodadora-1.jpg",
        informacion: 'La Rodadora es un museo interactivo y centro de ciencias ubicado en Ciudad Juárez, Chihuahua, México. Fundado en 2004, este museo ha sido un importante centro de aprendizaje y entretenimiento para personas de todas las edades en la región. A continuación, te proporcionaré un informe completo sobre el Museo La Rodadora, destacando sus características principales y su contribución a la comunidad. ',
        informacion2: "La Rodadora se inauguró en 2004 con el propósito de brindar a la comunidad de Ciudad Juárez y sus alrededores un espacio dedicado a la educación, la ciencia y la cultura. Desde su apertura, el museo ha evolucionado y se ha expandido continuamente para ofrecer nuevas exposiciones y programas educativos. ",
        horarios: "Los horarios de funcionamiento y los precios de entrada pueden variar según la temporada y las exposiciones temporales. Se recomienda verificar los detalles actuales en el sitio web oficial del museo antes de planificar una visita. ",
        direccion: "Calle Jesús Soltero Lozoya y Blvd. Teófilo Borunda, Del Norte, Comunitario Jarudo, 32652 Cd Juárez, Chih.",
        googleMaps: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3394.9499492810864!2d-106.4306998236102!3d31.68993617413683!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x86e75c320bf457f7%3A0x5e3f28d1f3b206f8!2sLa%20Rodadora%20Espacio%20Interactivo!5e0!3m2!1ses-419!2smx!4v1696299279410!5m2!1ses-419!2smx",
        sitioWeb: "http://www.larodadora.org/",
        facebook: "https://www.facebook.com/LaRodadora/",
        instagram: "https://www.instagram.com/larodadora/",
        tiktok: "https://www.tiktok.com/@larodadora ",
    },
    {
        nombre: "Museo de la Revolución en La Frontera",
        heroURL: './assets/heros/museo-de-la-revolucion-en-la-frontera.jpg',
        imagen: "./assets/Museo de la revolucion en la frontera 1.jpg",
        informacion: "La edificación atrae por sus contrastes arquitectónicos: Híbrido de múltiples elementos característicos de la arquitectura del siglo XIX. La ex aduana fue construida por el ingeniero Manuel Garfias entre 1885 y 1888 y su fin principal fue albergar la aduana fronteriza. Su inauguración formal se efectuó el 10 de septiembre de 1889, asistiendo como representante personal de Porfirio Díaz el Coronel Miguel Ahumada y el gobernador del estado Lauro Carrillo. ",
        informacion2: "Enmarcada por la avenidas 16 de septiembre, Benito Juárez, Vicente Guerrero y Francisco Villa emerge diferenciándose del contexto arquitectónico ubicado en el centro de Ciudad Juárez, un edificio conocido como la Ex Aduana, construcción que hoy alberga el Museo de la Revolución en la Frontera. ",
        horarios: "De martes a domingo de 9:00 a 17:00 horas. Los lunes permanece cerrado. Acceso gratuito.  Horario de Visitas Guiadas: De martes a viernes, de 9:00 a 17:00 horas. Duración de la Visita: 45 a 60 minutos. ",
        direccion: "Calle 16 de septiembre s/n Av. Juárez, Zona Centro Centro, 32000 Cd Juárez, Chih.",
        googleMaps: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3393.1684015643154!2d-106.48662722360866!3d31.7386040741148!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x86e75926dca66c2b%3A0x3adef4eb3d3b4a76!2sMuseo%20de%20la%20Revoluci%C3%B3n%20en%20la%20Frontera!5e0!3m2!1ses-419!2smx!4v1696299408172!5m2!1ses-419!2smx",
        sitioWeb: "https://sic.cultura.gob.mx/ficha.php?table=museo&table_id=1465", 
        gmail:"mailto:ifusioninah@yahoo.com.mx?Subject=Interesado en el servicio",
    },
    {
        nombre: "Monumento a la Mexicanidad",
        heroURL: "./assets/Monumento-a-la-mexicanidad-1.webp",
        imagen : "./assets/masonry-8.jpg",
        informacion: "Esta estructura metálica de color rojo intenso y en forma de X se yergue en la nueva Plaza de la Mexicanidad situada en el Parque Público Federal ‘El Chamizal’, en una franja de tierra que hace un poco más de medio siglo se ubicaba todavía entre Ciudad Juárez y el Río Bravo y pertenecía a los E.E.U.U. debido a que en los 1800s el río se desvió y esa parte se quedó de lado norteamericano. Si te encuentras en fechas de verano entre mayo y junio tienes la posibilidad de asistir a la feria más grande que realiza ciudad Juárez cada año, podrás encontrar desde los juegos mecánicos mas grandes de Latinoamérica, juegos pequeños para niños, música en vivo por grandes cantantes, una gran selección de platillos, entre otros.",
        informacion2: "Inaugurado el 24 de mayo de 2013 en la Plaza de la Mexicanidad, el Monumento a la Mexicanidad, también llamado “La X”, es una obra monumental de 64 metros de altura del artista mexicano Enrique Carbajal, mejor conocido por el nombre de Sebastián, autor de la famosísima escultura titulada “El Caballito” en el Paseo de Reforma de la ciudad de México.",
        horarios: "Los horarios de funcionamiento y los precios de entrada pueden variar según la temporada y las exposiciones temporales. Se recomienda verificar los detalles actuales.",
        direccion: "Chamizal, 32300 Cd Juárez, Chih.",
        googleMaps: "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d217338.40645712955!2d-106.5058589!3d31.6636108!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x86e759619e231103%3A0xe8de38234e9c7d08!2sPlaza%20de%20la%20Mexicanidad!5e0!3m2!1ses-419!2smx!4v1696383570747!5m2!1ses-419!2smx",
        sitioWeb: "",
        facebook: "",
        instagram: "",
        tiktok: "",
        gmail: "",
    },
    {
        nombre: "La Casa de Juan Gabriel",
        heroURL: "./assets/heros/casa-de-juan-gabriel-2.jpg",
        imagen : "./assets/casa-de-juan-gabriel-1.jpg",
        informacion: "Juan Gabriel es un personaje icónico de Cd. Juarez, aunque no haya nacido en la ciudad, sin duda se ha ganado el cariño de los habitantes juarenses, bautizado como “El divo de Juarez”, visita la famosa casa del cantante, y conoce aun mas de su historia en ciudad Juarez. En la actualidad la vivienda, que es conocida como Casa Victoria, es administrada por Silvia Urquidi, su manager y está adornada con varios cuadros y murales con su rostro. También destaca por su misticismo, pues cuenta con un cuarto secreto y con cajas fuertes ocultas, en donde el gran Juan Gabriel solía esconder parte de su fortuna.",
        informacion2: "Juan Gabriel, se mudó de niño a ciudad Juarez, debido a su madre, que trabajaba limpiando la propiedad en la que se le llama la casa de Juan Gabriel, y a los 16 años decidió salir a buscar dinero cantando, ya sea en restaurantes o en otros lugares, y es así donde empezó su carrera musical, y al ser grande y exitoso decidió comprarle la propiedad a su madre como símbolo de agradecimiento, y ahí estuvo viviendo con su madre hasta su muerte. DATO INTERESANTE: Juan Gabriel no nació en ciudad Juarez, nació en Michoacán.",
        horarios: "Los horarios de funcionamiento y los precios de entrada pueden variar según la temporada y las exposiciones temporales. Se recomienda verificar los detalles actuales.",
        direccion: "Perú 126, Partido Romero, 32030 Cd Juárez, Chih.",
        googleMaps:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3393.1630753516743!2d-106.4721704236086!3d31.738749474114826!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x86e759398213cdc3%3A0xc7f29fc7846194ba!2sCasa%20De%20Juan%20Gabriel!5e0!3m2!1ses-419!2smx!4v1696383626425!5m2!1ses-419!2smx",
        sitioWeb: "",
        facebook: "",
        instagram: "",
        tiktok: "",
        gmail: "",
    },
    {
        nombre: "Centro Cultural Paso del Norte",
        heroURL: "./assets/centro-cultural-paso-del-norte-1.jpg",
        imagen : "./assets/centro-cultural-paso-del-norte-2.webp",
        informacion: "Este espacio dedicado a las artes escénicas ofrece una amplia variedad de eventos a lo largo del año, desde conciertos de música rock hasta producciones de ópera reconocidas. El Centro Cultural Paso del Norte es un lugar de expresión artística, música y teatro ubicado en Ciudad Juárez. En él se llevan a cabo presentaciones de música clásica, interpretaciones de famosos ballets y otras propuestas originales. Es uno de los mejores espacios culturales de la ciudad. En el El Centro Cultural Paso del Norte, se puede observar con un mural de vidrio creado por la reconocida artista mexicana Patricia Baéz.",
        informacion2: "El centro cultural paso del norte es un centro de arte, música y teatro, en este puedes asistir a las presentaciones de música clásica, las interpretaciones de obras famosas de ballet y otros espectáculos originales. Este gran centro cuenta con muchas salas de espectáculos y exhibiciones. El auditorio principal es el teatro Víctor Hugo Rascón Banda, que cuenta con capacidad para 1,750 personas en tres niveles de asientos. También está el Teatro Experimental Octavio Trías, que tiene capacidad para 300 personas. Además de los teatros, hay varias salas de exhibiciones de arte, una biblioteca, un restaurante y un espacio para espectáculos al aire libre.",
        horarios: "Lunes: 9:00-3:00.\nMartes: 9:00-3:00.\nMiercoles: 9:00-3:00.\nJueves: 9:00-3:00.\nViernes: 9:00-3:00.\nSabado: 9:00-3:00.\nDomingo: 9:00-3:00.\n Los horarios de funcionamiento y los precios de entrada pueden variar según la temporada y las exposiciones temporales. Se recomienda verificar los detalles actuales.",
        direccion: "Anillo Envolvente del Pronaf, Zona Pronaf Condominio La Plata, 32315 Cd Juárez, Chih.",
        googleMaps:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3392.9833156838354!2d-106.44751802360845!3d31.743656374112426!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x86e759593f462ca5%3A0x38ac7595da728451!2sCentro%20Cultural%20Paso%20del%20Norte!5e0!3m2!1ses-419!2smx!4v1696383661979!5m2!1ses-419!2smx",
        sitioWeb: "https://sic.cultura.gob.mx/ficha.php?table=centro_cultural&table_id=1667",
        facebook: "https://www.facebook.com/ccpnoficial/",
        gmail: "mailto:atencionalclienteccpn@gmail.com?Subject=Interesado en el servicio",
        telefono: "656 617 1003",
    },
    {
        nombre: "El Chamizal",
        heroURL: "./assets/heros/el-chamizal-2.jpg",
        imagen : "./assets/museo-de-arqueologia-del-chamizal-1.jpg",
        informacion: "El Chamizal es el lugar de esparcimiento familiar y deportivo más importante con el que cuenta Juárez. El parque cuenta, a lo largo de toda su extensión, con una superficie totalmente reforestada similar a un bosque, además, también cuenta con un lago, canchas de fútbol, estadio olímpico, planta tratadora un invernadero y una red de ciclopistas esparcidas por todo el parque. Asimismo, el parque cuenta también con diversos monumentos históricos como el monumento 'El Chamizal', Monumento a los Niños Héroes, y el conocido Monumento a Benito Juárez, rodeado de un grande anillo de concreto, y a lo largo de él, placas conmemorativas con los escudos de cada estado de la república.",
        informacion2: "Originalmente formaba parte del territorio mexicano; sin embargo, por cambios en el cauce del río Bravo, quedó en el lado Norte del mismo, por lo que México entabló un largo litigio con los Estados Unidos para recuperarlo. Este territorio fue y es igualmente llamado Isla de Córdoba, por los dos afluentes del río Bravo que lo rodearon, el cauce original y el nuevo cauce derivado de una gran inundación en el siglo xix. Este territorio ha sido el único que Estados Unidos ha cedido a México aparte de la cesión del pueblo de Río Rico. ",
        horarios: "El parque publico esta abierto las 24 horas de los 7 dias de la semana. Se recomienda no estar en horarios nocturnos.",
        direccion: "Ing. David Herrera, C. Malecón, Chamizal, Cd Juárez, Chih.",
        googleMaps:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d13570.19771340812!2d-106.47874361284178!3d31.755497400000007!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x86e7596c1a6ad06f%3A0xdfb3c77a7b4776d7!2sParque%20P%C3%BAblico%20Federal%20El%20Chamizal!5e0!3m2!1ses-419!2smx!4v1696383695593!5m2!1ses-419!2smx",
        sitioWeb: "",
        facebook: "",
        instagram: "",
        tiktok: "",
        gmail: "",
        
    },
    {
        nombre: "Catedral de Nuestra Señora de Guadalupe",
        heroURL: "./assets/masonry-2.jpg",
        imagen : "./assets/catedral-2.jpg",
        informacion: "La catedral de Ciudad Juárez, dedicada a la Virgen de Guadalupe, se ubica en la ciudad fronteriza del estado de Chihuahua, en la zona denominada Centro Histórico. Fue levantada a mediados de la segunda mitad del siglo xx y se encuentra anexa a la antigua, y todavía conservada, misión franciscana, fundada en el siglo xvii, en el entonces Paso del Norte.Fue llamada 'La Reina de las Misiones' por el historiador Cleofas Calleros, ya que fue la primera misión en la zona. Fue fundada el 8 de diciembre de 1659 por Fray García de San Francisco y terminada el 15 de enero de 1668. Desde este lugar se procedió a la evangelización de los indígenas de la zona.",
        informacion2: "El edificio consta de una sola nave. El exterior, de estilo neoclásico, contrasta con el decorado del interior, muy austero. La portada principal tiene dos cuerpos: el primero, presenta dos pares de columnas estriadas, de capitel corintio, que enmarcan el arco de acceso, de medio punto; el segundo presenta otros dos pares de columnas, también corintias que enmarcan la ventana hexagonal del coro. Gruesas pilastras estriadas enmarcan los cuerpos, los cuales sostienen un frontón triangular, con un reloj en el centro de éste. Las dos torres, de tres cuerpos, son flanqueadas por columnas de fuste estriado. No se terminaron antes de la consagración del templo, sino hasta 1957.",
        horarios: "lunes, 9:30 a.m.–1p.m., 4–6:30 p.m. \nmartes, 9:30 a.m.–1 p.m., 4–6:30 p.m.\n miércoles, 9:30 a.m.–1 p.m., 4–6:30 p.m.\n jueves, 9:30 a.m.–1 p.m., 4–6:30 p.m.\n viernes, 9:30 a.m.–1 p.m., 4–6:30 p.m. \n sábado, 9:30 a.m.–1 p.m.\n domingo, Cerrado ",
        direccion: "Av Vicente Guerrero 101, Centro, 32000 Cd Juárez, Chih.",
        googleMaps:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3393.1624599419206!2d-106.4894110236087!3d31.738766274114774!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x86e759275aaa39b1%3A0xd030383125beb94!2sCatedral%20de%20Nuestra%20Se%C3%B1ora%20de%20Guadalupe!5e0!3m2!1ses-419!2smx!4v1696383736193!5m2!1ses-419!2smx",
        sitioWeb: "",
        facebook: "",
        instagram: "",
        tiktok: "",
        gmail: "",
        telefono: "656 615 5502",
    },
]